import "server-only";
import { z } from "zod";

const emptyStringToUndefined = (value: unknown) =>
  typeof value === "string" && value.trim() === "" ? undefined : value;

const optionalEnv = <T extends z.ZodType>(schema: T) =>
  z.preprocess(emptyStringToUndefined, schema.optional());

const serverSchema = z.object({
  DATABASE_URL: z.string().min(1),
  NEXTAUTH_URL: optionalEnv(z.string().url()),
  NEXTAUTH_SECRET: z.string().min(16),
  ADMIN_EMAIL: optionalEnv(z.string().email()),
  ADMIN_PASSWORD: optionalEnv(z.string().min(8)),
  NEXT_PUBLIC_HCAPTCHA_SITE_KEY: optionalEnv(z.string()),
  HCAPTCHA_SECRET_KEY: optionalEnv(z.string()),
  TELEGRAM_BOT_TOKEN: optionalEnv(z.string()),
  TELEGRAM_WEBHOOK_SECRET: optionalEnv(z.string().min(16)),
  REMNAWAVE_BASE_URL: optionalEnv(z.string().url()),
  REMNAWAVE_API_TOKEN: optionalEnv(z.string()),
  REMNAWAVE_DEFAULT_INBOUND_UUIDS: optionalEnv(z.string()),
  AUTO_PROVISION_ENABLED: optionalEnv(z.enum(["true", "false"])),
  AUTO_PROVISION_DRY_RUN: optionalEnv(z.enum(["true", "false"])),
  AUTO_PROVISION_TARGETS: optionalEnv(z.string()),
  AUTO_PROVISION_DOMAIN: optionalEnv(z.string()),
  AUTO_PROVISION_MEMBER_LIMIT: optionalEnv(z.coerce.number().int().positive()),
  AUTO_PROVISION_MAX_SERVERS: optionalEnv(z.coerce.number().int().positive()),
  AUTO_PROVISION_BATCH_SIZE: optionalEnv(z.coerce.number().int().positive()),
  AUTO_PROVISION_NODE_PORT: optionalEnv(z.coerce.number().int().positive()),
  AUTO_PROVISION_HOST_PORT: optionalEnv(z.coerce.number().int().positive()),
  AUTO_PROVISION_PANEL_IP: optionalEnv(z.string()),
  AUTO_PROVISION_CERTBOT_EMAIL: optionalEnv(z.string().email()),
  AUTO_PROVISION_SSH_USER: optionalEnv(z.string()),
  AUTO_PROVISION_SSH_PRIVATE_KEY_PATH: optionalEnv(z.string()),
  AUTO_PROVISION_SSH_CONNECT_TIMEOUT_SECONDS: optionalEnv(z.coerce.number().int().positive()),
  AUTO_PROVISION_REMNANODE_SECRET_KEY: optionalEnv(z.string().min(16)),
  AUTO_PROVISION_DOCKER_USERNAME: optionalEnv(z.string()),
  AUTO_PROVISION_DOCKER_TOKEN: optionalEnv(z.string()),
  AEZA_API_TOKEN: optionalEnv(z.string()),
  AEZA_PRODUCT_ID_AMSTERDAM: optionalEnv(z.string()),
  AEZA_PRODUCT_ID_VIENNA: optionalEnv(z.string()),
  AEZA_PRODUCT_ID_HELSINKI: optionalEnv(z.string()),
  AEZA_TERM: optionalEnv(z.string()),
  AEZA_AUTO_PROLONG: optionalEnv(z.enum(["true", "false"])),
  AEZA_OS_ID: optionalEnv(z.coerce.number().int().positive()),
  AEZA_RECIPE: optionalEnv(z.string()),
  AEZA_ORDER_PARAMETERS_JSON: optionalEnv(z.string()),
  TIMEWEB_CLOUD_TOKEN: optionalEnv(z.string()),
  TIMEWEB_DOMAIN: optionalEnv(z.string()),
  TIMEWEB_DNS_TTL: optionalEnv(z.coerce.number().int().positive()),
  CRON_SECRET: optionalEnv(z.string().min(16)),
  PAYMENTS_AUTO_APPROVE: optionalEnv(z.enum(["true", "false"])),
  YOOKASSA_SHOP_ID: optionalEnv(z.string()),
  YOOKASSA_SECRET_KEY: optionalEnv(z.string()),
  YOOKASSA_RETURN_URL: optionalEnv(z.string().url()),
  YOOKASSA_WEBHOOK_SECRET: optionalEnv(z.string().min(12)),
  SMTP_HOST: optionalEnv(z.string()),
  SMTP_CONNECT_HOST: optionalEnv(z.string()),
  SMTP_IP_FAMILY: optionalEnv(z.enum(["auto", "4", "6"])),
  SMTP_PORT: optionalEnv(z.coerce.number().int().positive()),
  SMTP_SECURE: optionalEnv(z.enum(["true", "false"])),
  SMTP_USER: optionalEnv(z.string()),
  SMTP_PASS: optionalEnv(z.string()),
  SMTP_FROM_EMAIL: optionalEnv(z.string().email()),
  SMTP_FROM_NAME: optionalEnv(z.string()),
  SUPPORT_EMAIL: optionalEnv(z.string().email()),
  NEXT_PUBLIC_OFFER_URL: optionalEnv(z.string().url()),
  NEXT_PUBLIC_PRIVACY_URL: optionalEnv(z.string().url()),
  NEXT_PUBLIC_SUPPORT_TELEGRAM_URL: optionalEnv(z.string().url()),
});

export const env = serverSchema.parse({
  DATABASE_URL: process.env.DATABASE_URL,
  NEXTAUTH_URL: process.env.NEXTAUTH_URL,
  NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
  ADMIN_EMAIL: process.env.ADMIN_EMAIL,
  ADMIN_PASSWORD: process.env.ADMIN_PASSWORD,
  NEXT_PUBLIC_HCAPTCHA_SITE_KEY: process.env.NEXT_PUBLIC_HCAPTCHA_SITE_KEY,
  HCAPTCHA_SECRET_KEY: process.env.HCAPTCHA_SECRET_KEY,
  TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN,
  TELEGRAM_WEBHOOK_SECRET: process.env.TELEGRAM_WEBHOOK_SECRET,
  REMNAWAVE_BASE_URL: process.env.REMNAWAVE_BASE_URL,
  REMNAWAVE_API_TOKEN: process.env.REMNAWAVE_API_TOKEN,
  REMNAWAVE_DEFAULT_INBOUND_UUIDS: process.env.REMNAWAVE_DEFAULT_INBOUND_UUIDS,
  AUTO_PROVISION_ENABLED: process.env.AUTO_PROVISION_ENABLED,
  AUTO_PROVISION_DRY_RUN: process.env.AUTO_PROVISION_DRY_RUN,
  AUTO_PROVISION_TARGETS: process.env.AUTO_PROVISION_TARGETS,
  AUTO_PROVISION_DOMAIN: process.env.AUTO_PROVISION_DOMAIN,
  AUTO_PROVISION_MEMBER_LIMIT: process.env.AUTO_PROVISION_MEMBER_LIMIT,
  AUTO_PROVISION_MAX_SERVERS: process.env.AUTO_PROVISION_MAX_SERVERS,
  AUTO_PROVISION_BATCH_SIZE: process.env.AUTO_PROVISION_BATCH_SIZE,
  AUTO_PROVISION_NODE_PORT: process.env.AUTO_PROVISION_NODE_PORT,
  AUTO_PROVISION_HOST_PORT: process.env.AUTO_PROVISION_HOST_PORT,
  AUTO_PROVISION_PANEL_IP: process.env.AUTO_PROVISION_PANEL_IP,
  AUTO_PROVISION_CERTBOT_EMAIL: process.env.AUTO_PROVISION_CERTBOT_EMAIL,
  AUTO_PROVISION_SSH_USER: process.env.AUTO_PROVISION_SSH_USER,
  AUTO_PROVISION_SSH_PRIVATE_KEY_PATH: process.env.AUTO_PROVISION_SSH_PRIVATE_KEY_PATH,
  AUTO_PROVISION_SSH_CONNECT_TIMEOUT_SECONDS:
    process.env.AUTO_PROVISION_SSH_CONNECT_TIMEOUT_SECONDS,
  AUTO_PROVISION_REMNANODE_SECRET_KEY: process.env.AUTO_PROVISION_REMNANODE_SECRET_KEY,
  AUTO_PROVISION_DOCKER_USERNAME: process.env.AUTO_PROVISION_DOCKER_USERNAME,
  AUTO_PROVISION_DOCKER_TOKEN: process.env.AUTO_PROVISION_DOCKER_TOKEN,
  AEZA_API_TOKEN: process.env.AEZA_API_TOKEN,
  AEZA_PRODUCT_ID_AMSTERDAM: process.env.AEZA_PRODUCT_ID_AMSTERDAM,
  AEZA_PRODUCT_ID_VIENNA: process.env.AEZA_PRODUCT_ID_VIENNA,
  AEZA_PRODUCT_ID_HELSINKI: process.env.AEZA_PRODUCT_ID_HELSINKI,
  AEZA_TERM: process.env.AEZA_TERM,
  AEZA_AUTO_PROLONG: process.env.AEZA_AUTO_PROLONG,
  AEZA_OS_ID: process.env.AEZA_OS_ID,
  AEZA_RECIPE: process.env.AEZA_RECIPE,
  AEZA_ORDER_PARAMETERS_JSON: process.env.AEZA_ORDER_PARAMETERS_JSON,
  TIMEWEB_CLOUD_TOKEN: process.env.TIMEWEB_CLOUD_TOKEN,
  TIMEWEB_DOMAIN: process.env.TIMEWEB_DOMAIN,
  TIMEWEB_DNS_TTL: process.env.TIMEWEB_DNS_TTL,
  CRON_SECRET: process.env.CRON_SECRET,
  PAYMENTS_AUTO_APPROVE: process.env.PAYMENTS_AUTO_APPROVE,
  YOOKASSA_SHOP_ID: process.env.YOOKASSA_SHOP_ID,
  YOOKASSA_SECRET_KEY: process.env.YOOKASSA_SECRET_KEY,
  YOOKASSA_RETURN_URL: process.env.YOOKASSA_RETURN_URL,
  YOOKASSA_WEBHOOK_SECRET: process.env.YOOKASSA_WEBHOOK_SECRET,
  SMTP_HOST: process.env.SMTP_HOST,
  SMTP_CONNECT_HOST: process.env.SMTP_CONNECT_HOST,
  SMTP_IP_FAMILY: process.env.SMTP_IP_FAMILY,
  SMTP_PORT: process.env.SMTP_PORT,
  SMTP_SECURE: process.env.SMTP_SECURE,
  SMTP_USER: process.env.SMTP_USER,
  SMTP_PASS: process.env.SMTP_PASS,
  SMTP_FROM_EMAIL: process.env.SMTP_FROM_EMAIL,
  SMTP_FROM_NAME: process.env.SMTP_FROM_NAME,
  SUPPORT_EMAIL: process.env.SUPPORT_EMAIL,
  NEXT_PUBLIC_OFFER_URL: process.env.NEXT_PUBLIC_OFFER_URL,
  NEXT_PUBLIC_PRIVACY_URL: process.env.NEXT_PUBLIC_PRIVACY_URL,
  NEXT_PUBLIC_SUPPORT_TELEGRAM_URL: process.env.NEXT_PUBLIC_SUPPORT_TELEGRAM_URL,
});
